### ISSUE TITLE
Goats stretched instead of cropped.

### ISSUE THREAD

**Issue by jtebert** [rosshettel/placegoat#1]
I was very excited to find this website, but I was hugely disappointed to discover that the images are stretched instead of cropped to create the appropriate size.

**Comment by rosshettel** [comment]
Sorry to hear about your disappointment, fellow goat aficionado! But you are right, the images are merely stretched and thus don't look so great at weird/large resolutions. 

I didn't consider it too high of a priority since this is a placeholder service, and hopefully the goat images wouldn't stick around for long wherever they are used. I'm open to pull requests though, if you'd like to fix it.

**Comment by rosshettel** [comment]
Hey @jtebert - I rewrote the app in node.js and while doing so decided to fix the stretched/skewed image issue. So hopefully this will work better for you!
